name: greenstem_workshop_mechanics
description: Demo module - Job Management for Workshop Mechanics (Greenstem WMS mobile MVP)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
