name: gearup_workshop_mechanics
description: GearUp Workshop - Job Management for Mechanics
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  uuid: ^4.4.0
  signature: ^5.5.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/   # 放登录页logo：assets/images/login_logo.png
